        SUBROUTINE FR(S0,NX1,NKX1,BETS)

C!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
C        SUBROUTINE FR CALCULATES THE FRESNEL REFLECTION FROM A NONOPAQUE
C        SURFACE. S0 N,NK,BETA PASSED.
C!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  

	DOUBLE PRECISION NX1,NKX1,S0,BETS,num,den

	num = (NX1 - 1.)**2 + NKX1**2
	den = (NX1 + 1.)**2 + NKX1**2
	S0 = BETS * num / den

	RETURN
        END
