meteoroids.pdf: meteoroids.tex
	xelatex -file-line-error -jobname=$(subst .pdf,,$@) -halt-on-error -interaction=nonstopmode meteoroids.tex 
	xelatex -file-line-error -jobname=$(subst .pdf,,$@) -halt-on-error -interaction=nonstopmode meteoroids.tex 
